import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../navbar'

const page4 = <div className="navBody page4"></div>

export default function Home() {
  return (
    <div className="page home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}
